### ISSUE TITLE
improve labels display

### ISSUE THREAD

**Issue by szydan** [sirensolutions/kibi_timeline_vis#14] opened 2016-04-08 10:59 UTC
When start and stop date are close the label is not visible inside tiny rectangle 
It will be better to display the label outside of rectangle 

At the same time make the rectangle for range events a bit smaller
and make sure that the label is clickable
<img width="440" alt="screen shot 2016-04-08 at 11 13 59" src="https://cloud.githubusercontent.com/assets/900118/14381854/548ef318-fd81-11e5-9c05-9e293f59cbae.png">

**Comment by rendel** [comment] 2016-05-12 10:05
test

**Comment by vinuja** [comment] 2016-06-27 10:02
I could be nice to be able to personalize the Event label with a text. 
Thanks

**Comment by scampi** [comment] 2016-06-27 10:30
@vinuja please open another issue for that, explaining what you would like.
Thanks!

**Comment by scampi** [comment] 2016-12-06 16:13
duplicate of https://github.com/sirensolutions/kibi_timeline_vis/issues/69
Let's track this issue over there.

**Closed by scampi** 2016-12-06 16:13 UTC
