### ISSUE TITLE
4.6.3: The number of values in the field [...] must be equal to the number of values in the field [...]

### ISSUE THREAD

**Issue by jfshiuan** [sirensolutions/kibi_timeline_vis#110] opened 2017-01-26 21:56 UTC
I'm using Kibana 4.6 (tried both 4.6.2 and 4.6.3), and I'm having problems with Kibi timeline 4.6.3.

The timeline works fine if I just specify the Event start date. As soon as I add an Event end date, I get a bunch of warnings: "Kibi Timeline: Check your data - the number of values in the field 'EndDate' must be equal to the number of values in the field 'CreateDate': document ID=[...]", and none of the events show up in the timeline.

The fields I'm using for the start and end dates are both single-value date fields. I even get the same error message when I use the same field for both start and end date. (i.e. "the number of values in the field 'EndDate' must be equal ... in the field 'EndDate'...")

Kibi timeline 4.5.4 seems to work fine on Kibana 4.6.

**Comment by SergeyBondarenko** [comment] 2017-01-27 13:44
Hello, @jfshiuan 
Could you share that part of your documents that contain start/end dates?

**Comment by SergeyBondarenko** [comment] 2017-01-27 14:42
@scampi Well, obviously the current issue is related to [this PR] (https://github.com/sirensolutions/kibi_timeline_vis/pull/97). I think the @jfshiuan has one or few documents with the number of values in the start field different from the number of values in the end field.
I remember the message _the number of values in the field 'EndDate' must be equal ... in the field 'EndDate'..._ appeared before this my PR. But it seems my code disrupted the message. There is no message visible anymore. The objects with a different number of start/end values are absent on the timeline. But all other objects are visible. 
Now we must decide what behavior we want to implement. Do we need to display the "correct" objects only (like it is now in the PR) plus this warning message?

**Comment by SergeyBondarenko** [comment] 2017-01-27 16:16
One correction, the warning message still works. I forgot to check the `Notify about errors in the data` checkbox.
![screenshot from 2017-01-27 17-14-52](https://cloud.githubusercontent.com/assets/5389745/22378022/4ae43ba0-e4b4-11e6-95b1-7d962c005827.png)

**Comment by jfshiuan** [comment] 2017-01-31 18:46
I've just created a index with just one document:
![image](https://cloud.githubusercontent.com/assets/5798361/22479258/eaaefe46-e7a1-11e6-8450-b68b4120d40c.png)

Search: 
{
  "query": {
    "match": {
      "Name": {
        "query": "Test Event",
        "type": "phrase"
      }
    }
  }
}

In 4.5.4 this works:
![screen shot 2017-01-31 at 10 29 22 am](https://cloud.githubusercontent.com/assets/5798361/22479329/335dfdf4-e7a2-11e6-83b0-f52426ab04ee.png)

In 4.6.3 it doesn't:
![screen shot 2017-01-31 at 10 36 00 am](https://cloud.githubusercontent.com/assets/5798361/22479343/418aef86-e7a2-11e6-9a65-106d7ac580cb.png)

**Comment by fabiocorneti** [comment] 2017-02-02 16:28
Please try the latest release at https://github.com/sirensolutions/kibi_timeline_vis/releases .

**Comment by SergeyBondarenko** [comment] 2017-02-06 13:17
@jfshiuan Have you tried [the latest release](https://github.com/sirensolutions/kibi_timeline_vis/releases)? Does it work for you?

**Comment by jfshiuan** [comment] 2017-02-07 18:32
Just tried it. Still having the same issue.

**Comment by SergeyBondarenko** [comment] 2017-02-08 08:58
@jfshiuan I can't reproduce your issue. Can I have SSH access to the server to look at your data? Actually, we can look together interactively via [GNU screen](https://www.gnu.org/software/screen/). If it is impossible, could you please check some of your data for me?

1. Execute the following command, you need to substitude `localhost` with IP address of your Elasticsearch and `9200` with it's current port.
```
curl -XGET localhost:9200/.kibi/search/_search?pretty -d @'{"query":{"match":{"title":"Test Search"}}, "size": 10000}'
```
2. Among the results, find a document with exact `"title" : "Test Search"`. 

- Get its `searchSourceJSON` field value. It must be a long JSON format string of the following format `"{\"index\":\"YOUR_INDEX_NAME\", ...}"`. 
- Copy all this string. 
- Delete `\"index\":\"YOUR_INDEX_NAME\",` from it. 
- Put `"size": 10000` before the last closing curly bracket `}`. 
In the end the string must look like this: `{\"query\":{ ALL_OTHER_DATA }, "size": 10000}`.

3. Execute the following command:.
```
curl -XGET localhost:9200/YOUR_INDEX_NAME/_search?pretty -d @'THE_STRING_FROM_THE_STEP_ABOVE'
``` 
4. Share the results of the command above.

**Comment by jfshiuan** [comment] 2017-02-09 20:51
I'm using Kibana 4.6.3 by the way, not Kibi.

searchSourceJSON: "{\"index\":\"test_index\",\"query\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}},\"filter\":[{\"meta\":{\"negate\":false,\"index\":\"test_index\",\"key\":\"Name\",\"value\":\"Test Event\",\"disabled\":false,\"alias\":null},\"query\":{\"match\":{\"Name\":{\"query\":\"Test Event\",\"type\":\"phrase\"}}},\"$state\":{\"store\":\"appState\"}}],\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"require_field_match\":false,\"fragment_size\":2147483647}}"

If I follow step 2 exactly I get a query_parsing_exception (No query registered for [meta]).

If I delete the "filter":[{"meta":.....}] part and try again, I get:
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test_index",
        "_type": "test_event",
        "_id": "AVokcrk5N-IqxkqM1Idn",
        "_score": 1,
        "_source": {
          "EndDate": "2016-10-31T00:00:00.000000",
          "@timestamp": "2016-10-01T00:00:00.000000",
          "StartDate": "2016-10-01T00:00:00.000000",
          "Name": "Test Event"
        }
      }
    ]
  }
}

**Comment by SergeyBondarenko** [comment] 2017-02-15 09:22
@jfshiuan I can reproduce the issue. It will be resolved soon.

**Closed** 2017-02-23 13:23 UTC
Labels: bug
